version: "3.7"

services:
    php:
        build:
            context: ${PHP_7_PATH}
        restart: "always"
        ports:
            - 9000:9000
        volumes:
            - ./www:/var/www
            - ${PHP_7_PATH}/config/www.conf:/etc/php7/php-fpm.d/www.conf
        environment:
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
        depends_on:
            - db
        networks:
            -   local
    
    nginx:
        image: "nginx:${NGINX_VERSION}"
        restart: "always"
        ports:
            - 8000:80
        volumes:
            - ./www:/var/www
            - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - db
        networks:
            - local

    db:
        image: "mysql:${MYSQLDB_VERSION}"
        restart: "always"
        ports:
            - 3306:3306
        volumes:
            - ./mysql/db:/var/lib/mysql   
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
        networks:
            - local


networks:
    local:
        driver: bridge